//
// Created by Andy Best on 14/03/2016.
// Copyright (c) 2016 andybest. All rights reserved.
//

import Foundation

extension CPU6502 {

    typealias AM = AddressingModeRef

    func buildInstructionTable() {
        let nopEntry = InstructionEntry(instructionName: "NOP", instructionFunction: opNOP, addressingMode: AM.Implicit,
                numBytes: 1, numCycles: 2, specialCycles: false)

        instructionTable = [InstructionEntry](count: 256, repeatedValue: nopEntry)
        add6502Opcodes()
    }

    func addInstruction(opcode: UInt8, ins: (AddressingMode) -> (Void), insName: String,
                        addrMode: AddressingModeRef, numBytes: Int, numCycles: Int, specialCycles: Bool) {
        instructionTable[Int(opcode)] = InstructionEntry(instructionName: insName, instructionFunction: ins,
                addressingMode: addrMode, numBytes: numBytes, numCycles: numCycles, specialCycles: specialCycles)
    }

    func add6502Opcodes() {
        addInstruction(0x00, ins: opBRK, insName:"BRK", addrMode: AM.Implicit, numBytes: 1, numCycles: 7, specialCycles: false)
        addInstruction(0x01, ins: opORA, insName:"ORA", addrMode: AM.IndirectX, numBytes: 2, numCycles: 6, specialCycles: false)
        addInstruction(0x05, ins: opORA, insName:"ORA", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 3, specialCycles: false)
        addInstruction(0x06, ins: opASL, insName:"ASL", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 5, specialCycles: false)
        addInstruction(0x08, ins: opPHP, insName:"PHP", addrMode: AM.Implicit, numBytes: 1, numCycles: 3, specialCycles: false)
        addInstruction(0x09, ins: opORA, insName:"ORA", addrMode: AM.Accumulator, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0x0D, ins: opORA, insName:"ORA", addrMode: AM.Absolute, numBytes: 3, numCycles: 4, specialCycles: false)
        addInstruction(0x0E, ins: opASL, insName:"ASL", addrMode: AM.Absolute, numBytes: 3, numCycles: 6, specialCycles: false)
        addInstruction(0x10, ins: opBPL, insName:"BPL", addrMode: AM.Relative, numBytes: 2, numCycles: 2, specialCycles: true)
        addInstruction(0x11, ins: opORA, insName:"ORA", addrMode: AM.IndirectY, numBytes: 2, numCycles: 5, specialCycles: true)
        addInstruction(0x15, ins: opORA, insName:"ORA", addrMode: AM.ZeroPageX, numBytes: 2, numCycles: 4, specialCycles: false)
        addInstruction(0x16, ins: opASL, insName:"ASL", addrMode: AM.ZeroPageX, numBytes: 2, numCycles: 6, specialCycles: false)
        addInstruction(0x18, ins: opCLC, insName:"CLC", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0x19, ins: opORA, insName:"ORA", addrMode: AM.AbsoluteY, numBytes: 3, numCycles: 4, specialCycles: true)
        addInstruction(0x1D, ins: opORA, insName:"ORA", addrMode: AM.AbsoluteX, numBytes: 3, numCycles: 4, specialCycles: true)
        addInstruction(0x1E, ins: opASL, insName:"ASL", addrMode: AM.AbsoluteX, numBytes: 3, numCycles: 7, specialCycles: false)
        addInstruction(0x20, ins: opJSR, insName:"JSR", addrMode: AM.Absolute, numBytes: 3, numCycles: 6, specialCycles: false)
        addInstruction(0x21, ins: opAND, insName:"AND", addrMode: AM.IndirectX, numBytes: 2, numCycles: 6, specialCycles: false)
        addInstruction(0x24, ins: opBIT, insName:"BIT", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 3, specialCycles: false)
        addInstruction(0x25, ins: opAND, insName:"AND", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 3, specialCycles: false)
        addInstruction(0x26, ins: opROL, insName:"ROL", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 5, specialCycles: false)
        addInstruction(0x28, ins: opPLP, insName:"PLP", addrMode: AM.Implicit, numBytes: 1, numCycles: 4, specialCycles: false)
        addInstruction(0x29, ins: opAND, insName:"AND", addrMode: AM.Immediate, numBytes: 2, numCycles: 2, specialCycles: false)
        addInstruction(0x2A, ins: opROL, insName:"ROL", addrMode: AM.Accumulator, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0x2C, ins: opBIT, insName:"BIT", addrMode: AM.Absolute, numBytes: 3, numCycles: 4, specialCycles: false)
        addInstruction(0x2D, ins: opAND, insName:"AND", addrMode: AM.Absolute, numBytes: 3, numCycles: 4, specialCycles: false)
        addInstruction(0x2E, ins: opROL, insName:"ROL", addrMode: AM.Absolute, numBytes: 3, numCycles: 6, specialCycles: false)
        addInstruction(0x30, ins: opBMI, insName:"BMI", addrMode: AM.Relative, numBytes: 2, numCycles: 2, specialCycles: true)
        addInstruction(0x31, ins: opAND, insName:"AND", addrMode: AM.IndirectY, numBytes: 2, numCycles: 5, specialCycles: true)
        addInstruction(0x35, ins: opAND, insName:"AND", addrMode: AM.ZeroPageX, numBytes: 2, numCycles: 4, specialCycles: false)
        addInstruction(0x36, ins: opROL, insName:"ROL", addrMode: AM.ZeroPageX, numBytes: 2, numCycles: 6, specialCycles: false)
        addInstruction(0x38, ins: opSEC, insName:"SEC", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0x39, ins: opAND, insName:"AND", addrMode: AM.AbsoluteY, numBytes: 3, numCycles: 4, specialCycles: true)
        addInstruction(0x3D, ins: opAND, insName:"AND", addrMode: AM.AbsoluteX, numBytes: 3, numCycles: 4, specialCycles: true)
        addInstruction(0x3E, ins: opROL, insName:"ROL", addrMode: AM.AbsoluteX, numBytes: 3, numCycles: 7, specialCycles: false)
        addInstruction(0x40, ins: opRTI, insName:"RTI", addrMode: AM.Implicit, numBytes: 1, numCycles: 6, specialCycles: false)
        addInstruction(0x41, ins: opEOR, insName:"EOR", addrMode: AM.IndirectX, numBytes: 2, numCycles: 6, specialCycles: false)
        addInstruction(0x45, ins: opEOR, insName:"EOR", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 3, specialCycles: false)
        addInstruction(0x46, ins: opLSR, insName:"LSR", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 5, specialCycles: false)
        addInstruction(0x48, ins: opPHA, insName:"PHA", addrMode: AM.Implicit, numBytes: 1, numCycles: 3, specialCycles: false)
        addInstruction(0x49, ins: opEOR, insName:"EOR", addrMode: AM.Immediate, numBytes: 2, numCycles: 2, specialCycles: false)
        addInstruction(0x4A, ins: opLSR, insName:"LSR", addrMode: AM.Accumulator, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0x4C, ins: opJMP, insName:"JMP", addrMode: AM.Absolute, numBytes: 3, numCycles: 3, specialCycles: false)
        addInstruction(0x4D, ins: opEOR, insName:"EOR", addrMode: AM.Absolute, numBytes: 3, numCycles: 4, specialCycles: false)
        addInstruction(0x4E, ins: opLSR, insName:"LSR", addrMode: AM.Absolute, numBytes: 3, numCycles: 6, specialCycles: false)
        addInstruction(0x50, ins: opBVC, insName:"BVC", addrMode: AM.Relative, numBytes: 2, numCycles: 2, specialCycles: true)
        addInstruction(0x51, ins: opEOR, insName:"EOR", addrMode: AM.IndirectY, numBytes: 2, numCycles: 5, specialCycles: true)
        addInstruction(0x55, ins: opEOR, insName:"EOR", addrMode: AM.ZeroPageX, numBytes: 2, numCycles: 4, specialCycles: false)
        addInstruction(0x56, ins: opLSR, insName:"LSR", addrMode: AM.ZeroPageX, numBytes: 2, numCycles: 6, specialCycles: false)
        addInstruction(0x58, ins: opCLI, insName:"CLI", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0x59, ins: opEOR, insName:"EOR", addrMode: AM.AbsoluteY, numBytes: 3, numCycles: 4, specialCycles: true)
        addInstruction(0x5D, ins: opEOR, insName:"EOR", addrMode: AM.AbsoluteX, numBytes: 3, numCycles: 4, specialCycles: true)
        addInstruction(0x5E, ins: opLSR, insName:"LSR", addrMode: AM.AbsoluteX, numBytes: 3, numCycles: 7, specialCycles: false)
        addInstruction(0x60, ins: opRTS, insName:"RTS", addrMode: AM.Implicit, numBytes: 1, numCycles: 6, specialCycles: false)
        addInstruction(0x61, ins: opADC, insName:"ADC", addrMode: AM.IndirectX, numBytes: 2, numCycles: 6, specialCycles: false)
        addInstruction(0x65, ins: opADC, insName:"ADC", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 3, specialCycles: false)
        addInstruction(0x66, ins: opROR, insName:"ROR", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 5, specialCycles: false)
        addInstruction(0x68, ins: opPLA, insName:"PLA", addrMode: AM.Implicit, numBytes: 1, numCycles: 4, specialCycles: false)
        addInstruction(0x69, ins: opADC, insName:"ADC", addrMode: AM.Immediate, numBytes: 2, numCycles: 2, specialCycles: false)
        addInstruction(0x6A, ins: opROR, insName:"ROR", addrMode: AM.Accumulator, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0x6C, ins: opJMP, insName:"JMP", addrMode: AM.Indirect, numBytes: 3, numCycles: 5, specialCycles: false)
        addInstruction(0x6D, ins: opADC, insName:"ADC", addrMode: AM.Absolute, numBytes: 3, numCycles: 4, specialCycles: false)
        addInstruction(0x6E, ins: opROR, insName:"ROR", addrMode: AM.Absolute, numBytes: 3, numCycles: 6, specialCycles: false)
        addInstruction(0x70, ins: opBVS, insName:"BVS", addrMode: AM.Relative, numBytes: 2, numCycles: 2, specialCycles: true)
        addInstruction(0x71, ins: opADC, insName:"ADC", addrMode: AM.IndirectY, numBytes: 2, numCycles: 5, specialCycles: true)
        addInstruction(0x75, ins: opADC, insName:"ADC", addrMode: AM.ZeroPageX, numBytes: 2, numCycles: 4, specialCycles: false)
        addInstruction(0x76, ins: opROR, insName:"ROR", addrMode: AM.ZeroPageX, numBytes: 2, numCycles: 6, specialCycles: false)
        addInstruction(0x78, ins: opSEI, insName:"SEI", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0x79, ins: opADC, insName:"ADC", addrMode: AM.AbsoluteY, numBytes: 3, numCycles: 4, specialCycles: true)
        addInstruction(0x7D, ins: opADC, insName:"ADC", addrMode: AM.AbsoluteX, numBytes: 3, numCycles: 4, specialCycles: true)
        addInstruction(0x7E, ins: opROR, insName:"ROR", addrMode: AM.AbsoluteX, numBytes: 3, numCycles: 7, specialCycles: false)
        addInstruction(0x81, ins: opSTA, insName:"STA", addrMode: AM.IndirectX, numBytes: 2, numCycles: 6, specialCycles: false)
        addInstruction(0x84, ins: opSTY, insName:"STY", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 3, specialCycles: false)
        addInstruction(0x85, ins: opSTA, insName:"STA", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 3, specialCycles: false)
        addInstruction(0x86, ins: opSTX, insName:"STX", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 3, specialCycles: false)
        addInstruction(0x88, ins: opDEY, insName:"DEY", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0x8A, ins: opTXA, insName:"TXA", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0x8C, ins: opSTY, insName:"STY", addrMode: AM.Absolute, numBytes: 3, numCycles: 4, specialCycles: false)
        addInstruction(0x8D, ins: opSTA, insName:"STA", addrMode: AM.Absolute, numBytes: 3, numCycles: 4, specialCycles: false)
        addInstruction(0x8E, ins: opSTX, insName:"STX", addrMode: AM.Absolute, numBytes: 3, numCycles: 4, specialCycles: false)
        addInstruction(0x90, ins: opBCC, insName:"BCC", addrMode: AM.Relative, numBytes: 2, numCycles: 2, specialCycles: true)
        addInstruction(0x91, ins: opSTA, insName:"STA", addrMode: AM.IndirectY, numBytes: 2, numCycles: 6, specialCycles: false)
        addInstruction(0x94, ins: opSTY, insName:"STY", addrMode: AM.ZeroPageX, numBytes: 2, numCycles: 4, specialCycles: false)
        addInstruction(0x95, ins: opSTA, insName:"STA", addrMode: AM.ZeroPageX, numBytes: 2, numCycles: 4, specialCycles: false)
        addInstruction(0x96, ins: opSTX, insName:"STX", addrMode: AM.ZeroPageY, numBytes: 2, numCycles: 4, specialCycles: false)
        addInstruction(0x98, ins: opTYA, insName:"TYA", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0x99, ins: opSTA, insName:"STA", addrMode: AM.AbsoluteY, numBytes: 3, numCycles: 5, specialCycles: false)
        addInstruction(0x9A, ins: opTXS, insName:"TXS", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0x9D, ins: opSTA, insName:"STA", addrMode: AM.AbsoluteX, numBytes: 3, numCycles: 5, specialCycles: false)
        addInstruction(0xA0, ins: opLDY, insName:"LDY", addrMode: AM.Immediate, numBytes: 2, numCycles: 2, specialCycles: false)
        addInstruction(0xA1, ins: opLDA, insName:"LDA", addrMode: AM.IndirectX, numBytes: 2, numCycles: 6, specialCycles: false)
        addInstruction(0xA2, ins: opLDX, insName:"LDX", addrMode: AM.Immediate, numBytes: 2, numCycles: 2, specialCycles: false)
        addInstruction(0xA4, ins: opLDY, insName:"LDY", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 3, specialCycles: false)
        addInstruction(0xA5, ins: opLDA, insName:"LDA", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 3, specialCycles: false)
        addInstruction(0xA6, ins: opLDX, insName:"LDX", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 3, specialCycles: false)
        addInstruction(0xA8, ins: opTAY, insName:"TAY", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0xA9, ins: opLDA, insName:"LDA", addrMode: AM.Immediate, numBytes: 2, numCycles: 2, specialCycles: false)
        addInstruction(0xAA, ins: opTAX, insName:"TAX", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0xAC, ins: opLDY, insName:"LDY", addrMode: AM.Absolute, numBytes: 3, numCycles: 4, specialCycles: false)
        addInstruction(0xAD, ins: opLDA, insName:"LDA", addrMode: AM.Absolute, numBytes: 3, numCycles: 4, specialCycles: false)
        addInstruction(0xAE, ins: opLDX, insName:"LDX", addrMode: AM.Absolute, numBytes: 3, numCycles: 4, specialCycles: false)
        addInstruction(0xB0, ins: opBCS, insName:"BCS", addrMode: AM.Relative, numBytes: 2, numCycles: 2, specialCycles: true)
        addInstruction(0xB1, ins: opLDA, insName:"LDA", addrMode: AM.IndirectY, numBytes: 2, numCycles: 5, specialCycles: true)
        addInstruction(0xB4, ins: opLDY, insName:"LDY", addrMode: AM.ZeroPageX, numBytes: 2, numCycles: 4, specialCycles: false)
        addInstruction(0xB5, ins: opLDA, insName:"LDA", addrMode: AM.ZeroPageX, numBytes: 2, numCycles: 4, specialCycles: false)
        addInstruction(0xB6, ins: opLDX, insName:"LDX", addrMode: AM.ZeroPageY, numBytes: 2, numCycles: 4, specialCycles: false)
        addInstruction(0xB8, ins: opCLV, insName:"CLV", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0xB9, ins: opLDA, insName:"LDA", addrMode: AM.AbsoluteY, numBytes: 3, numCycles: 4, specialCycles: true)
        addInstruction(0xBA, ins: opTSX, insName:"TSX", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0xBC, ins: opLDY, insName:"LDY", addrMode: AM.AbsoluteX, numBytes: 3, numCycles: 4, specialCycles: true)
        addInstruction(0xBD, ins: opLDA, insName:"LDA", addrMode: AM.AbsoluteX, numBytes: 3, numCycles: 4, specialCycles: true)
        addInstruction(0xBE, ins: opLDX, insName:"LDX", addrMode: AM.AbsoluteY, numBytes: 3, numCycles: 4, specialCycles: true)
        addInstruction(0xC0, ins: opCPY, insName:"CPY", addrMode: AM.Immediate, numBytes: 2, numCycles: 2, specialCycles: false)
        addInstruction(0xC1, ins: opCMP, insName:"CMP", addrMode: AM.IndirectX, numBytes: 2, numCycles: 6, specialCycles: false)
        addInstruction(0xC4, ins: opCPY, insName:"CPY", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 3, specialCycles: false)
        addInstruction(0xC5, ins: opCMP, insName:"CMP", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 3, specialCycles: false)
        addInstruction(0xC6, ins: opDEC, insName:"DEC", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 5, specialCycles: false)
        addInstruction(0xC8, ins: opINY, insName:"INY", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0xC9, ins: opCMP, insName:"CMP", addrMode: AM.Immediate, numBytes: 2, numCycles: 2, specialCycles: false)
        addInstruction(0xCA, ins: opDEX, insName:"DEX", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0xCC, ins: opCPY, insName:"CPY", addrMode: AM.Absolute, numBytes: 3, numCycles: 4, specialCycles: false)
        addInstruction(0xCD, ins: opCMP, insName:"CMP", addrMode: AM.Absolute, numBytes: 3, numCycles: 4, specialCycles: false)
        addInstruction(0xCE, ins: opDEC, insName:"DEC", addrMode: AM.Absolute, numBytes: 3, numCycles: 6, specialCycles: false)
        addInstruction(0xD0, ins: opBNE, insName:"BNE", addrMode: AM.Relative, numBytes: 2, numCycles: 2, specialCycles: true)
        addInstruction(0xD1, ins: opCMP, insName:"CMP", addrMode: AM.IndirectY, numBytes: 2, numCycles: 5, specialCycles: true)
        addInstruction(0xD5, ins: opCMP, insName:"CMP", addrMode: AM.ZeroPageX, numBytes: 2, numCycles: 4, specialCycles: false)
        addInstruction(0xD6, ins: opDEC, insName:"DEC", addrMode: AM.ZeroPageX, numBytes: 2, numCycles: 6, specialCycles: false)
        addInstruction(0xD8, ins: opCLD, insName:"CLD", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0xD9, ins: opCMP, insName:"CMP", addrMode: AM.AbsoluteY, numBytes: 3, numCycles: 4, specialCycles: true)
        addInstruction(0xDD, ins: opCMP, insName:"CMP", addrMode: AM.AbsoluteX, numBytes: 3, numCycles: 4, specialCycles: true)
        addInstruction(0xDE, ins: opDEC, insName:"DEC", addrMode: AM.AbsoluteX, numBytes: 3, numCycles: 7, specialCycles: false)
        addInstruction(0xE0, ins: opCPX, insName:"CPX", addrMode: AM.Immediate, numBytes: 2, numCycles: 2, specialCycles: false)
        addInstruction(0xE1, ins: opSBC, insName:"SBC", addrMode: AM.IndirectX, numBytes: 2, numCycles: 6, specialCycles: false)
        addInstruction(0xE4, ins: opCPX, insName:"CPX", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 3, specialCycles: false)
        addInstruction(0xE5, ins: opSBC, insName:"SBC", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 3, specialCycles: false)
        addInstruction(0xE6, ins: opINC, insName:"INC", addrMode: AM.ZeroPage, numBytes: 2, numCycles: 5, specialCycles: false)
        addInstruction(0xE8, ins: opINX, insName:"INX", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0xE9, ins: opSBC, insName:"SBC", addrMode: AM.Immediate, numBytes: 2, numCycles: 2, specialCycles: false)
        addInstruction(0xEA, ins: opNOP, insName:"NOP", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0xEC, ins: opCPX, insName:"CPX", addrMode: AM.Absolute, numBytes: 3, numCycles: 4, specialCycles: false)
        addInstruction(0xED, ins: opSBC, insName:"SBC", addrMode: AM.Absolute, numBytes: 3, numCycles: 4, specialCycles: false)
        addInstruction(0xEE, ins: opINC, insName:"INC", addrMode: AM.Absolute, numBytes: 3, numCycles: 6, specialCycles: false)
        addInstruction(0xF0, ins: opBEQ, insName:"BEQ", addrMode: AM.Relative, numBytes: 2, numCycles: 2, specialCycles: true)
        addInstruction(0xF1, ins: opSBC, insName:"SBC", addrMode: AM.IndirectY, numBytes: 2, numCycles: 5, specialCycles: true)
        addInstruction(0xF5, ins: opSBC, insName:"SBC", addrMode: AM.ZeroPageX, numBytes: 2, numCycles: 4, specialCycles: false)
        addInstruction(0xF6, ins: opINC, insName:"INC", addrMode: AM.ZeroPageX, numBytes: 2, numCycles: 6, specialCycles: false)
        addInstruction(0xF8, ins: opSED, insName:"SED", addrMode: AM.Implicit, numBytes: 1, numCycles: 2, specialCycles: false)
        addInstruction(0xF9, ins: opSBC, insName:"SBC", addrMode: AM.AbsoluteY, numBytes: 3, numCycles: 4, specialCycles: true)
        addInstruction(0xFD, ins: opSBC, insName:"SBC", addrMode: AM.AbsoluteX, numBytes: 3, numCycles: 4, specialCycles: true)
        addInstruction(0xFE, ins: opINC, insName:"INC", addrMode: AM.AbsoluteX, numBytes: 3, numCycles: 7, specialCycles: false)
    }
}
